name: Using Artifacts

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v3.1.2
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Check files
        run: |
          ls
          ./hello

  test-linux:
    name: Test artifact on linux
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: linux

      - name: Check files
        run: |
          ls
          ./hello
